version: "3.9"

services:

  deeppavlov-cpu:
    environment:
      - CONFIG=ner_ontonotes_bert_mult
    healthcheck:
      test: python -c "import requests; requests.post('http://localhost:5000/probe', json={}).json() == ['Test passed']"
    networks:
      - annotators
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - "deeppavlov:/root/.deeppavlov"

  deeppavlov-gpu:
    environment:
      - CONFIG=ner_ontonotes_bert_mult
    healthcheck:
      test: python -c "import requests; requests.post('http://localhost:5000/probe', json={}).json() == ['Test passed']"
    networks:
      - annotators
    ports:
      - "5000:5000"
    restart: on-failure
    runtime: "nvidia"
    volumes:
      - "deeppavlov:/root/.deeppavlov"

  floods:
    env_file:
      - ./annotators/floods/.env
    command: flask run --host=0.0.0.0 --port=5001
    networks:
      - annotators
    ports:
      - "5001:5001"
    restart: on-failure
    volumes:
      - "floods:/opt/floods/models"

  fires:
    networks:
      - annotators
    ports:
      - "5002:5002"
    restart: on-failure
    volumes:
      - "${PWD}/annotators/fires/models:/app/models"

networks:
  annotators:
    attachable: true

volumes:
  deeppavlov:
  floods:
